name: Docker-publish

on:
  push:
    tags:
      - v*

env:
  IMAGE_NAME: docker-topsap

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Set the value
        id: step_one
        run: |
          echo 'TAG_VERSION=libra146/docker-topsap:$(echo \"${{ github.ref }}\" | sed -e "s,.*/\(.*\),\1,")' >> "$GITHUB_ENV"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: libra146
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: libra146/docker-topsap:{{ env.TAG_VERSION }}

      - name: Build and push latest
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: libra146/docker-topsap:latest
